In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,3])
print(arr)

[1 2 3 3]


In [3]:
a = [12,3]
a

[12, 3]

In [4]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [7]:
np.array(l)

array([1, 2, 3, 4])

In [33]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr = np.zeros((6,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr1 = np.ones((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr = np.linspace(1,20,20)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [42]:
np.random.rand(5) #normalisation between 0 and 1

array([0.6742052 , 0.708505  , 0.51810707, 0.51442527, 0.40980754])

In [43]:
np.random.randn(5) #standardisation between -3 and 3

array([ 0.23859854,  1.67977981, -1.59735361, -0.29279631,  0.49947231])

In [49]:
np.random.randint(1,10,10,int)

array([2, 5, 9, 5, 1, 2, 5, 7, 7, 3], dtype=int32)

In [55]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr.shape
arr.size

9

In [58]:
arr.dtype

dtype('int64')

In [59]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr.min().item()

1

In [65]:
arr.max().item()

9

In [67]:
arr.sum().item()

45

In [68]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [69]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [71]:
arr.mean().item()

5.0

In [72]:
arr.std().item()

2.581988897471611

In [81]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr.argmin().item()

0

In [83]:
arr.argmax()

np.int64(8)

In [86]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [89]:
arr = arr.reshape(5,6)

In [90]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [91]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr.size

10

In [93]:
arr.dtype

dtype('int64')

In [95]:
arr.shape

(10,)

In [98]:
arr.max().item()

10

In [99]:
arr.min().item()

1

In [101]:
arr.sum().item()


55

In [104]:
arr.mean().item()

5.5

In [105]:
arr.std().item()

2.8722813232690143

In [106]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
arr.argmin().item()

0

In [110]:
arr.argmax().item()

8

In [117]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [118]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [120]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [122]:
arr[6].item() #indexing

17

In [125]:
arr[3:] #slicing

array([14, 15, 16, 17, 18, 19, 20])

In [126]:
arr[2::2]

array([13, 15, 17, 19])

In [128]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [129]:
arr[0]

array([1, 2, 3, 4, 5])

In [130]:
arr[4]

array([21, 22, 23, 24, 25])

In [131]:
np.sum(arr, axis = 0)

array([ 81,  87,  93,  99, 105])

In [132]:
arr[1,4]

np.int64(10)

In [135]:
slice = arr[2:4 , 2:4]
slice

array([[13, 14],
       [18, 19]])

In [136]:
arr[3: , 3:] 

array([[19, 20],
       [24, 25],
       [29, 30]])

In [139]:
arr[3,4]

np.int64(20)

In [140]:
arr.min().item()

1

In [141]:
arr.max().item()

30

In [142]:
np.sum(arr , axis = 1)

array([ 15,  40,  65,  90, 115, 140])

In [143]:
arr.argmin().item()

0

In [144]:
arr.argmax().item()

29

In [145]:
arr.mean().item()

15.5

In [159]:
arr = np.arange(11,41)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [160]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [162]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [6]:
import numpy as np
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [7]:
arr = a1 + a2
arr

array([ 7,  9, 11, 13, 15])

In [8]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [9]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [13]:
arr = np.array([10,20,30,40])
arr + 10

array([20, 30, 40, 50])

In [14]:
arr - 1

array([ 9, 19, 29, 39])

In [17]:
arr = np.arange(1,26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [19]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
arr + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [21]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
arr2 = arr + 10
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [24]:
arr1 = np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [27]:
arr4 = arr1 + 10
arr4

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [28]:
arr4 * 2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

In [29]:
arr = np.arange(1,26)
arr 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [33]:
slice = arr[0:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [37]:
arr[4:6] * 10

array([50, 60])

In [38]:
arr*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250])

In [39]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
arr = arr1
arr1[0] = 100

In [45]:
arr1[0] = 100

In [46]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [47]:
A

array([[1, 2],
       [3, 4]])

In [48]:
B

array([[5, 6],
       [7, 8]])

In [49]:
A+B

array([[ 6,  8],
       [10, 12]])

In [50]:
A-B

array([[-4, -4],
       [-4, -4]])

In [51]:
A*B

array([[ 5, 12],
       [21, 32]])

In [52]:
A@B

array([[19, 22],
       [43, 50]])

In [54]:
A

array([[1, 2],
       [3, 4]])

In [55]:
A.T

array([[1, 3],
       [2, 4]])

In [56]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [57]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [2]:
np.row_stack((a,b))

NameError: name 'np' is not defined

In [62]:
arr = np.arange(0,16).reshape(4,4)
arr
                            

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.hsplit(arr , 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [66]:
np.vsplit(arr, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [67]:
np.vsplit(arr, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [69]:
#valid sudoku numpy practice exercise

In [73]:
arr = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [74]:
arr.sum()

np.int64(405)

In [83]:
b = np.sum(arr ,  axis = 1)
for i in b:
    if i != 45:
        print("sudoku is  valid")
        break
else:
    print("sudoku for rows is valid")

sudoku for rows is valid


In [84]:
np.sum(arr , axis = 0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [87]:
arr1 = arr[0:3,0:3]
arr1

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [89]:
arr1.sum().item()

45

In [90]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i: i + 3 , j: j + 3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [174]:
#age , maths marks , science marks
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [175]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [152]:
data.size

15

In [153]:
data.sum()

np.int64(916)

In [154]:
data[0:5 , 0].mean().item()

18.4

In [155]:
data[:,1]

array([85, 92, 76, 65, 90])

In [156]:
data[:,2].max().item()

95

In [157]:
data[data[:,1] > 90]

array([[19, 92, 88]])

In [158]:
data = data[:,1] + 5
data

array([90, 97, 81, 70, 95])

In [167]:
data.shape

(5, 3)

In [168]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [178]:
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [179]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [194]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])

In [195]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [196]:
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])

In [3]:
import os

print(os.getcwd())

C:\Users\Joy Singla
